export enum EPermission {
  LIRE_RECLAMATIONS = 'LIRE_RECLAMATIONS',
  CREER_RECLAMATIONS = 'CREER_RECLAMATIONS',
  MODIFIER_RECLAMATIONS = 'MODIFIER_RECLAMATIONS',
  SUPPRIMER_RECLAMATIONS = 'SUPPRIMER_RECLAMATIONS',
  ASSIGNER_RECLAMATIONS = 'ASSIGNER_RECLAMATIONS',
  LIRE_UTILISATEURS = 'LIRE_UTILISATEURS',
  CREER_UTILISATEURS = 'CREER_UTILISATEURS',
  MODIFIER_UTILISATEURS = 'MODIFIER_UTILISATEURS',
  SUPPRIMER_UTILISATEURS = 'SUPPRIMER_UTILISATEURS',
  GERER_ACCES = 'GERER_ACCES',
  CONSULTER_RAPPORTS = 'CONSULTER_RAPPORTS',
  VOIR_NOUVELLES_RECLAMATIONS = 'VOIR_NOUVELLES_RECLAMATIONS',
  GERER_EQUIPE = 'GERER_EQUIPE',
  CREER_EQUIPE = 'CREER_EQUIPE'
}

export interface Access {
  id?: number;
  name: string;
  permissions: EPermission[];
  createdAt?: string;
  updatedAt?: string;
  deleted?: boolean;
}
